version: '3'
services:
  webrtc:
    stdin_open: true
    build:
      context: master
    container_name: master-server
    working_dir: "/app"
    net: "host"
    #ports:
    #  - 8000:8000
    volumes:
      - ./master/app/html:/app/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
  rtsp:
    stdin_open: true
    build:
      context: slave
    container_name: slave-camera
    working_dir: "/app"
    ports:
      - 8554:8554
    command: -G 640x480x30 -S
    devices:
      - "/dev/video0:/dev/video0"
    extra_hosts:
      - "host.docker.internal:host-gateway"