version: '3'
services:
  webrtc:
    stdin_open: true
    build:
      context: .
    container_name: master-server
    working_dir: "/app"
    network_mode: "host"
    volumes:
      - ./master/app/html:/app/html
    extra_hosts:
      - "host.docker.internal:host-gateway"